name: openai_test
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.2

# Add regular dependencies here.
dependencies:
  dart_openai: ^4.0.0
  envied: ^0.3.0+3
  dio: ^5.3.3
  json_annotation: ^4.8.1
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.6
  build_web_compilers: ^4.0.0
  envied_generator: ^0.3.0+3
  json_serializable: ^6.7.1
  lints: ^2.0.0
